version: '3.0'
services:
  rasa:
    image: rasa/rasa:3.2.0-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  app:
    image: yspeech/bierbot-rasa-actions:latest
    expose: 
      - 5055
