
version: '3.7'
services:

  rasa:
    image: rasa/rasa:3.2.0-full
    volumes:
      - ./:/app
    ports: 
      - 5005:5005
#    entrypoint: ["/bin/sh", "-c", "rasa train && rasa run"]
    command:
      - run
    user: root

  app:
    image: yspeech/bierbot-rasa-actions:latest
    ports:
      - 5055:5055
  
volumes: 
  traefik-public-certificates:

networks:
  traefik-public:
    external: true
