version: "3.7"
services:
  rasa-server: # The chatbot backend
    container_name: rasa-server
    # image: rasa/rasa:3.2.0-full
    image: khalosa/rasa-aarch64 # works on M1 macs
    entrypoint: ["/bin/sh", "-c"]
    command:
      - "rasa run --cors '*'"
    working_dir: /app
    user: nonroot